feat: реализована логика по получению общих фильмов, отсортированных …
NLazutkin/java-filmorate pull request #10
Opened 2024-10-09 18:43 UTC by asyachem

…по популярности

2024-10-09 21:27 UTC, NLazutkin commented on src/main/java/ru/yandex/practicum/filmorate/enums/query/FilmQueries.java
> +                            "GROUP BY f.id"),
1. Сейчас код реализует RIGHT JOIN лайков (почему RIGHT?) и тут же выполняется подзапрос к лайкам. Это выглядит нелогично. Поясни пожалуйста суть.
2. Не проверяется существует ли пользователь или фильм. Если ссылочная целостность по каким-либо причинам будет нарушена, то будут непредвиденные исключения. Например кто-то удалил пользователя, а его лайки не удалили. Соответственно подзапрос вернет лайки пользователя который не существует.

Решения тут два. 
- Либо сделать findFilm() и findUser()  в методе findCommonFilms() по аналогии с другими методами класса 
- Либо в запросе сделать JOIN фильмов, лайков, пользователей.

2024-10-09 21:27 UTC, NLazutkin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        filmsUser.retainAll(filmsFriend);
Сначала выполняется поиск фильмов пользователя и их преобразование к DTO (fillFilmData с кучей запросов к остальным данным фильма), затем тоже самое для друга, а только потом выполняется сбор общих фильмов. Т.е. получается, что могут быть и не общие фильмы и в итоговый список они не войдут, но "тяжелый "fillFilmData мы для них сделаем. Логичнее сначала получить список общих пользователей, а затем его преобразовать fillFilmData.

2024-10-09 21:27 UTC, NLazutkin commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        return userFilms;
Мне кажется было бы хорошим тоном воспользоваться в данном случае Stream API

2024-10-10 06:16 UTC, asyachem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        return userFilms;
Справедливо, сделаю

2024-10-10 06:30 UTC, asyachem commented on src/main/java/ru/yandex/practicum/filmorate/enums/query/FilmQueries.java
> +                            "GROUP BY f.id"),
1. спасибо, что обратил внимание. код я здесь забыла подчистить. хотела убрать строку с join и оставить подзапрос, но видимо этот момент просмотрела. 
2. проверку на существующего юзера сделаю

2024-10-10 11:17 UTC, NLazutkin submitted a review, later dismissed

2024-10-10 11:29 UTC, verigi approved these changes

2024-10-10 12:27 UTC, NLazutkin requested changes
В целом ок.

2024-10-10 12:54 UTC, NLazutkin approved these changes

2024-10-10 12:57 UTC, merged