Реализация функционала "Рекомендации"
NLazutkin/java-filmorate pull request #14
Opened 2024-10-10 15:12 UTC by verigi

2024-10-10 16:38 UTC, NLazutkin requested changes

2024-10-10 16:38 UTC, NLazutkin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +}
Перенеси пожалуйста этот метод в UserService, эта логика скорее нужна там. И соответственно заинжекти UserStorage.

2024-10-10 16:39 UTC, asyachem approved these changes
reviewed

2024-10-11 18:50 UTC, NLazutkin approved these changes

2024-10-11 18:51 UTC, merged