Реализация модели Director("Режиссер")
NLazutkin/java-filmorate pull request #8
Opened 2024-10-09 08:16 UTC by NLazutkin

2024-10-09 18:06 UTC, dante-must-die submitted a review, later dismissed
Имя переменной в методе findDirector называется genreId, хотя по факту это directorId.

А так вроде все

2024-10-10 11:20 UTC, verigi approved these changes, later dismissed

2024-10-10 12:39 UTC, verigi submitted a review, later dismissed
Reviewed

2024-10-10 12:46 UTC, dante-must-die requested changes, later dismissed
reviewed

2024-10-10 13:07 UTC, asyachem requested changes
Reviewed

2024-10-10 13:18 UTC, verigi approved these changes

2024-10-10 13:32 UTC, asyachem approved these changes
Reviewed

2024-10-10 14:10 UTC, merged